NucData/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^core/', include('core.urls', namespace='core')),
    url(r'^isotopes/',include('isotopes.urls', namespace='isotopes')),
    url(r'^nucreactions/',include('nucreactions.urls', namespace='nucreactions')),
    url(r'^elementary_particles/',include('elementaryparticles.urls', namespace='elementaryparticles')),
    url(r'^radiations/',include('radiations.urls', namespace='radiations'))
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^signup', views.signup, name='signup'),
]

isotopes/urls.py
from django.conf.urls import url
from . import views

app_name = 'isotopes'

urlpatterns = [
    url(r'^iso/add_isotopes/', views.add_isotopes, name='add_isotopes'),
    url(r'^iso/(?P<pk>\d+)/$', views.IsotopeDetailView.as_view(), name='isotope-detail'),
    url(r'^iso/', views.IsotopeListView.as_view(), name='isotopes')
]

nucreactions/urls.py
from django.conf.urls import url
from . import views

app_name = 'nucreations'

urlpatterns = [
    url(r'^reactions/add_reactions/', views.add_reactions, name='add_reactions'),
    url(r'^reactions/(?P<pk>\d+)/$', views.ReactionDetailView.as_view(), name='reaction-detail'),
    url(r'^reactions/', views.ReactionListView.as_view(), name='reactions')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>Isotopes</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width = device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'isotopes:add_isotopes' %}">Add isotopes</a></li>
          <li><a href="{% url 'isotopes:isotopes' %}">Get all isotopes</a></li>
          <li><a href="{% url 'nucreactions:reactions' %}">Get all reactions</a></li>
          <li><a href="{% url 'nucreactions:add_reactions' %}">Add reactions</a></li>
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            <li><a href="{% url 'core:signup'%}">Sign up</a></li>
          {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Isotope Library Home</h1>


  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Isotopes:</strong> {{ num_isotopes }}</li>
    <li><strong>Reactions:</strong> {{ num_reactions }}</li>
  </ul>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}